import Image from "next/image";
import { Link } from "@/i18n/navigation";

/**
 * The lockup artwork is 324x61. Height is driven by --logo-h so each surface
 * can size it without touching the aspect ratio.
 *
 * NOTE: logo-white.png is DERIVED, not official — it was generated by forcing
 * every visible pixel white. HANDOFF flags getting a sanctioned reversed
 * lockup from the association as production work.
 */
export function Logo({
  variant = "dark",
  className,
  priority = false,
}: {
  variant?: "dark" | "white";
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={variant === "white" ? "/brand/logo-white.png" : "/brand/logo.png"}
      alt="Jordan Restaurant Association"
      width={324}
      height={61}
      priority={priority}
      className={className}
    />
  );
}

export function LogoLink({
  variant = "dark",
  className,
}: {
  variant?: "dark" | "white";
  className?: string;
}) {
  return (
    <Link href="/" className={className} aria-label="Jordan Restaurant Association">
      <Logo variant={variant} priority />
    </Link>
  );
}
