import restaurantsJson from "@/data/restaurants.json";
import suppliersJson from "@/data/suppliers.json";
import vocabJson from "@/data/vocab.json";

/**
 * Static directory data, generated by scripts/extract-data.py from the
 * nopCommerce xlsx exports. There is no backend: everything below is bundled
 * at build time and filtered on the client.
 */

/** Fields shared by both directories. */
export interface DirectoryEntry {
  slug: string;
  name: string;
  address: string;
  city: string;
  tags: string[];
  blurb: string;
  /** Venue logo (Picture1 in the export). May be empty. */
  logo: string;
  /** Primary photograph (Picture2). Empty for entries with no photography. */
  image: string;
  image2: string;
}

export interface Restaurant extends DirectoryEntry {
  cuisine: string;
}

/**
 * Opening hours, indexed 0 = Sunday (the Jordanian working week starts Sunday).
 * `null` means closed that day.
 *
 * NOT IN THE SOURCE EXPORT. The nopCommerce data carries no hours at all, so
 * the profile page renders a documented sample pattern and labels it as
 * unconfirmed on screen. It is deliberately one shared shape rather than
 * per-restaurant invention: a plausible-looking unique schedule per venue would
 * be indistinguishable from real data, and someone would eventually turn up at
 * a closed restaurant because of it.
 */
export const SAMPLE_HOURS: Array<{ open: string; close: string } | null> = [
  { open: "12:00", close: "23:00" }, // Sun
  { open: "12:00", close: "23:00" },
  { open: "12:00", close: "23:00" },
  { open: "12:00", close: "23:00" },
  { open: "12:00", close: "00:30" }, // Thu
  { open: "13:00", close: "00:30" }, // Fri
  { open: "12:00", close: "23:00" }, // Sat
];

/**
 * Google Maps search link built from the venue name and address. Used instead
 * of an embedded map because the export has no coordinates and embedding needs
 * a billed API key — this is a real, working link with neither.
 */
export function mapsUrl(entry: DirectoryEntry): string {
  const query = [entry.name, entry.address, "Jordan"].filter(Boolean).join(", ");
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

/** Every usable photograph for an entry, deduplicated. */
export function photosOf(entry: DirectoryEntry): string[] {
  return [entry.image, entry.image2, entry.logo].filter(
    (src, index, all) => src && all.indexOf(src) === index,
  );
}

export interface Supplier extends DirectoryEntry {
  trade: string;
}

export interface Vocab {
  cuisines: string[];
  trades: string[];
  cities: string[];
  features: string[];
  featured: string[];
  totals: {
    restaurants: number;
    suppliers: number;
    cuisines: number;
    trades: number;
    governorates: number;
    features: number;
  };
}

export const restaurants = restaurantsJson as Restaurant[];
export const suppliers = suppliersJson as Supplier[];
export const vocab = vocabJson as Vocab;

const restaurantBySlug = new Map(restaurants.map((r) => [r.slug, r]));
const supplierBySlug = new Map(suppliers.map((s) => [s.slug, s]));

export function getRestaurant(slug: string): Restaurant | undefined {
  return restaurantBySlug.get(slug);
}

export function getSupplier(slug: string): Supplier | undefined {
  return supplierBySlug.get(slug);
}

/** The hand-picked venues promoted to the home page rail, in curated order. */
export function featuredRestaurants(): Restaurant[] {
  return vocab.featured
    .map((slug) => restaurantBySlug.get(slug))
    .filter((r): r is Restaurant => Boolean(r));
}

// ---------------------------------------------------------------------------
// Filtering
// ---------------------------------------------------------------------------

export interface DirectoryQuery {
  q?: string;
  /** Cuisine for restaurants, trade for suppliers. */
  category?: string;
  city?: string;
  feature?: string;
}

function haystack(entry: Restaurant | Supplier): string {
  const category = "cuisine" in entry ? entry.cuisine : entry.trade;
  return [entry.name, category, entry.city, entry.address, ...entry.tags]
    .join(" ")
    .toLowerCase();
}

/**
 * Case- and diacritic-insensitive match. Arabic users routinely type without
 * diacritics and with alef variants (أ إ آ vs ا), so those are folded before
 * comparing — otherwise a search for "الاردن" misses "الأردن".
 */
function fold(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[ً-ْٰ]/g, "") // Arabic diacritics
    .replace(/[آأإ]/g, "ا") // alef variants -> bare alef
    .replace(/ة/g, "ه") // teh marbuta -> heh
    .replace(/ى/g, "ي") // alef maqsura -> yeh
    .replace(/[̀-ͯ]/g, ""); // latin combining marks
}

export function filterEntries<T extends Restaurant | Supplier>(
  entries: T[],
  query: DirectoryQuery,
): T[] {
  const q = query.q ? fold(query.q.trim()) : "";

  return entries.filter((entry) => {
    if (q && !fold(haystack(entry)).includes(q)) return false;

    if (query.category) {
      const category = "cuisine" in entry ? entry.cuisine : entry.trade;
      if (category !== query.category) return false;
    }

    if (query.city && entry.city !== query.city) return false;

    if (query.feature) {
      const want = fold(query.feature);
      if (!entry.tags.some((tag) => fold(tag) === want)) return false;
    }

    return true;
  });
}

// ---------------------------------------------------------------------------
// Search suggestions (home hero + header)
// ---------------------------------------------------------------------------

export type SuggestionKind =
  | "restaurant"
  | "supplier"
  | "cuisine"
  | "trade"
  | "governorate"
  | "feature";

/**
 * Structured rather than a raw href string: next-intl's router resolves a
 * string href as a pathname only and silently drops any `?query`, so a
 * suggestion like "Italian" has to carry its filter separately to survive
 * navigation.
 */
export interface SuggestionHref {
  pathname: string;
  query?: Record<string, string>;
}

export interface Suggestion {
  label: string;
  kind: SuggestionKind;
  href: SuggestionHref;
}

/** Built once per module load rather than per keystroke. */
const suggestionIndex: Array<Suggestion & { haystack: string }> = [
  ...restaurants.map((r) => ({
    label: r.name,
    kind: "restaurant" as const,
    href: { pathname: `/restaurants/${r.slug}` },
    haystack: fold(haystack(r)),
  })),
  ...suppliers.map((s) => ({
    label: s.name,
    kind: "supplier" as const,
    href: { pathname: `/suppliers/${s.slug}` },
    haystack: fold(haystack(s)),
  })),
  ...vocab.cuisines.map((c) => ({
    label: c,
    kind: "cuisine" as const,
    href: { pathname: "/restaurants", query: { category: c } },
    haystack: fold(c),
  })),
  ...vocab.trades.map((t) => ({
    label: t,
    kind: "trade" as const,
    href: { pathname: "/suppliers", query: { category: t } },
    haystack: fold(t),
  })),
  ...vocab.cities.map((c) => ({
    label: c,
    kind: "governorate" as const,
    href: { pathname: "/restaurants", query: { city: c } },
    haystack: fold(c),
  })),
  ...vocab.features.map((f) => ({
    label: f,
    kind: "feature" as const,
    href: { pathname: "/restaurants", query: { feature: f } },
    haystack: fold(f),
  })),
];

/** Fires at 2+ characters, capped at 6 results to keep the panel scannable. */
export function suggest(term: string, limit = 6): Suggestion[] {
  const q = fold(term.trim());
  if (q.length < 2) return [];

  const out: Suggestion[] = [];
  for (const item of suggestionIndex) {
    if (item.haystack.includes(q)) {
      out.push({ label: item.label, kind: item.kind, href: item.href });
      if (out.length >= limit) break;
    }
  }
  return out;
}
