// Generated by tools/extract.py from the nopCommerce xlsx exports.
// Photos are hotlinked from jra.jo for mockup purposes only.
const JRA_DATA = {
  "restaurants": [
    {
      "name": "Reem Al Bawadi",
      "address": "Waha cirlce, Reem Al Bawadi Restaurant, Mohammad Al Fayyad Al Assaf Street 63, Amman",
      "cuisine": "Local / Jordanian Food",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Kids friendly",
        "Parking",
        "Smart / Casual"
      ],
      "blurb": "Reem Al Bawadi is a huge restaurant complex popular with tour groups and Jordanian families. It's a bit far from the center but is a good option if you want to try some upper-end Jordanian and Lebanese food. Menu include",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0012205_reem-al-bawadi.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0012206_reem-al-bawadi.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0012207_reem-al-bawadi.jpeg"
    },
    {
      "name": "Zaatar W Zeit",
      "address": "Mecca St & Madineh St",
      "cuisine": "Lebanese",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Outdoor catering",
        "Outdoor dining",
        "Parking"
      ],
      "blurb": "",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0002287_zaatar-w-zeit.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0002288_zaatar-w-zeit.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0002288_zaatar-w-zeit.jpeg"
    },
    {
      "name": "Shams El Balad",
      "address": "Mu'Ath Bin Jabal Street 69, Jabal Amman, Amman 11181",
      "cuisine": "Local / Jordanian Food",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Kids friendly",
        "live music and dj",
        "Outdoor dining"
      ],
      "blurb": "Shams was first founded in December 2000 as a small shop selling handmade pots and plants by Maha Dahmash, an avid self-taught gardener and florist. Over the course of twenty years, this family business has grown with th",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0009163_shams-el-balad.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0009164_shams-el-balad.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0009165_shams-el-balad.jpeg"
    },
    {
      "name": "Romero Restaurant",
      "address": "Romero Restaurant / The Living Room Restaurant, Mohammad Hussein Haykal Street, 3rd circle , Amman",
      "cuisine": "Italian",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Outdoor catering",
        "Outdoor dining",
        "Serve alcohol"
      ],
      "blurb": "Let us take you on a journey back in time; the year 1921, a young doctor by the name of Fausto Tesio established the Italian Hospital in the heart of the new city near the ancient Roman Amphitheatre. Deeply inspired by h",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0008111_romero-restaurant.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0008112_romero-restaurant.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0008113_romero-restaurant.jpeg"
    },
    {
      "name": "Peking",
      "address": "Abdelhamid badees street, Shemsani Amman",
      "cuisine": "Chinese",
      "category": "Restaurants",
      "tags": [
        "Kids friendly",
        "Parking",
        "Smart / Casual",
        "Smoke free indoor area"
      ],
      "blurb": "Peking Restaurant opened its doors in 1987. One of Amman's first fine dining establishments, the restaurant fast became a favorite among Jordanians and tourists alike. Peking serves a range of exotic Chinese plates cooke",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0012233_peking.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0012234_peking.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0012235_peking.jpeg"
    },
    {
      "name": "Vintage Restaurant",
      "address": "Queen Rania St., Amman, Jordan",
      "cuisine": "International",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Outdoor dining",
        "Soft music",
        "tv screen"
      ],
      "blurb": "We believe that a great café experience goes beyond the beverages and food, It's about creating ♥️",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0018494_vintage-restaurant.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0018495_vintage-restaurant.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0018496_vintage-restaurant.jpeg"
    },
    {
      "name": "Abu Jbara",
      "address": "Madina Munawara St 189, Amman, Jordan",
      "cuisine": "Local / Jordanian Food",
      "category": "Restaurants",
      "tags": [
        "Kids friendly",
        "Outdoor dining",
        "Parking",
        "Soft music"
      ],
      "blurb": "",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0006013_abu-jbara.png",
      "image": "https://jra.jo/content/images/thumbs/0006010_abu-jbara.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0006011_abu-jbara.jpeg"
    },
    {
      "name": "Arabica Jordan",
      "address": "Arabica Amman The Boulevard// Arabica Amman Swefieh Village",
      "cuisine": "Coffee House",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Parking",
        "Smart / Casual",
        "Wheelchair access"
      ],
      "blurb": "Independent coffee brand from Kyoto for cosmopolitan souls. It’s about our simple love for coffee, design, and #seetheworldthroughcoffee",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0017373_arabica-jordan.png",
      "image": "https://jra.jo/content/images/thumbs/0017374_arabica-jordan.png",
      "image2": "https://jra.jo/content/images/thumbs/0017375_arabica-jordan.png"
    },
    {
      "name": "Al Mankal",
      "address": "Gardens (Main Branch)/ Sweifieh/ Tabarbour/ Hai Nazzal/ Abu Alanda/ Marj Al Hamam/ Sweileh/ Aqaba/ Jabal Al Nasr/",
      "cuisine": "Local / Jordanian Food",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Kids meal",
        "Casual Dress",
        "Delivery"
      ],
      "blurb": "",
      "city": "Aqaba",
      "logo": "https://jra.jo/content/images/thumbs/0018282_al-mankal.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0018283_al-mankal.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0018284_al-mankal.jpeg"
    },
    {
      "name": "Ararat Restaurant",
      "address": "Armenian Cuisine Restaurant",
      "cuisine": "International",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Soft music",
        "Take-away",
        "Valet"
      ],
      "blurb": "",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0002567_ararat-restaurant.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0002568_ararat-restaurant.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0002568_ararat-restaurant.jpeg"
    },
    {
      "name": "Fame Restaurant",
      "address": "28 Suleiman Al Hadeedi Amman, Jordan",
      "cuisine": "International",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "live music and dj",
        "Outdoor dining",
        "Serve alcohol"
      ],
      "blurb": "Fame Restaurant in Amman blends international cuisine with Japanese flair. Enjoy sushi, steaks, pasta & seafood in a refined setting. Don’t miss our 30% lunch discount (12–5 PM), Happy Hour (7–9 PM), and sushi buffet on ",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0017696_fame-restaurant.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0017557_fame-restaurant.jpeg",
      "image2": "https://jra.jo/content/images/thumbs/0017558_fame-restaurant.jpeg"
    },
    {
      "name": "2 Bites Burgers & Sides",
      "address": "7th roundabout-- Dabouq",
      "cuisine": "Fast Food (Quick Service)",
      "category": "Restaurants",
      "tags": [
        "Good for groups",
        "Kids friendly",
        "Outdoor dining",
        "Parking"
      ],
      "blurb": "",
      "city": "Amman",
      "logo": "https://jra.jo/content/images/thumbs/0004943_2-bites-burgers-sides.jpeg",
      "image": "https://jra.jo/content/images/thumbs/0004940_2-bites-burgers-sides.png",
      "image2": "https://jra.jo/content/images/thumbs/0004941_2-bites-burgers-sides.png"
    }
  ],
  "cuisines": [
    "Local / Jordanian Food",
    "Fast Food (Quick Service)",
    "Yemini",
    "Lebanese",
    "Bakeries and Patisseries",
    "International",
    "Chinese",
    "Japanese and Sushi",
    "Indian",
    "Italian",
    "French",
    "American",
    "Seafood",
    "Steakhouse",
    "Health Food",
    "Pizza",
    "Others",
    "Coffee House",
    "Portuguese",
    "Iraqi",
    "Turkish",
    "Thai"
  ],
  "cities": [
    "Amman",
    "Irbid",
    "Zarqa",
    "Aqaba",
    "Petra",
    "Dead Sea",
    "Jerash",
    "Madaba",
    "Salt",
    "Ajloun",
    "Karak",
    "Almafraq",
    "Azraq",
    "Fuhais",
    "Ramtha",
    "Wadi Rum",
    "Ma'an"
  ],
  "features": [
    "Accept Booking",
    "Outdoor dining",
    "Indoor dining",
    "Parking",
    "Delivery",
    "Good for groups",
    "Family place",
    "Kids friendly",
    "Casual dress",
    "Credit card accepted",
    "Reservations",
    "Shisha (Argeeleh)",
    "Serves alcohol",
    "Live music",
    "Soft music",
    "Catering",
    "Wheelchair accessible",
    "Breakfast",
    "Lunch",
    "Dinner"
  ],
  "totalRestaurants": 757
};
