/**
 * Seeds RestaurantImage / SupplierImage rows from the jra.jo image URLs held
 * in the front end's directory snapshot.
 *
 * WHY NOT 03-images.ts
 * --------------------
 * That script maps image files out of the JRA / JRA-moreassets reference
 * folders, which are hundreds of megabytes and not in the repo. Without them
 * every listing renders imageless. The front end's dataset already carries the
 * live jra.jo URLs for the same pictures, and next.config.ts whitelists
 * jra.jo / www.jra.jo as remote image hosts — so those URLs are usable
 * directly and need no local assets.
 *
 * Slot order is preserved exactly as the original export had it —
 * logo (Picture1), image (Picture2), image2 (Picture3) — as sortOrder 0/1/2
 * with no primary flag, so regenerating the snapshot round-trips to the same
 * three slots.
 *
 * Source path is overridable with LEGACY_DIRECTORY_JSON_DIR; it defaults to
 * the sibling front-end checkout.
 */
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { db } from "@/lib/db";

type Entry = { slug: string; name: string; logo?: string; image?: string; image2?: string };

const SOURCE_DIR =
  process.env.LEGACY_DIRECTORY_JSON_DIR ??
  path.join(process.cwd(), "..", "JRA", "web", "data");

function load(file: string): Entry[] {
  const full = path.join(SOURCE_DIR, file);
  if (!existsSync(full)) {
    throw new Error(
      `Missing ${full}. Set LEGACY_DIRECTORY_JSON_DIR to the folder holding restaurants.json / suppliers.json.`,
    );
  }
  return JSON.parse(readFileSync(full, "utf8")) as Entry[];
}

/** Loose key so a slug generated by a different slugifier still matches. */
function nameKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function slotsOf(entry: Entry): string[] {
  return [entry.logo, entry.image, entry.image2]
    .map((v) => (v ?? "").trim())
    .filter((v, i, all) => v && all.indexOf(v) === i);
}

async function seed(
  kind: "restaurant" | "supplier",
  entries: Entry[],
  rows: { id: string; slug: string; name: string }[],
  replace: (id: string, urls: string[]) => Promise<void>,
) {
  const bySlug = new Map(rows.map((r) => [r.slug, r]));
  const byName = new Map(rows.map((r) => [nameKey(r.name), r]));

  let matched = 0;
  let imaged = 0;
  let unmatched = 0;

  for (const entry of entries) {
    const row = bySlug.get(entry.slug) ?? byName.get(nameKey(entry.name));
    if (!row) {
      unmatched++;
      continue;
    }
    matched++;

    const urls = slotsOf(entry);
    if (!urls.length) continue;

    await replace(row.id, urls);
    imaged++;
  }

  console.log(`✓ ${kind}s matched: ${matched}, given images: ${imaged}, unmatched: ${unmatched}`);
}

async function main() {
  const [restaurantRows, supplierRows] = await Promise.all([
    db.restaurant.findMany({ select: { id: true, slug: true, name: true } }),
    db.supplier.findMany({ select: { id: true, slug: true, name: true } }),
  ]);

  await seed("restaurant", load("restaurants.json"), restaurantRows, async (id, urls) => {
    await db.restaurantImage.deleteMany({ where: { restaurantId: id, legacyPath: "jra.jo" } });
    await db.restaurantImage.createMany({
      data: urls.map((url, i) => ({
        restaurantId: id,
        url,
        sortOrder: i,
        isPrimary: false,
        legacyPath: "jra.jo",
      })),
    });
  });

  await seed("supplier", load("suppliers.json"), supplierRows, async (id, urls) => {
    await db.supplierImage.deleteMany({ where: { supplierId: id } });
    await db.supplierImage.createMany({
      data: urls.map((url, i) => ({ supplierId: id, url, sortOrder: i, isPrimary: false })),
    });
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
